### ISSUE TITLE
bin/bash: bad interpreter when executing install.sh

### ISSUE THREAD

**Issue by chillywit** [petercreyghton/ogn-install#2]
I get /bin/bash: bad interpreter: no such file or directory error when executing ./install.sh from ogn-install directory.  I can see the install.sh file in the directory.  I'm new to R.pi and not a programmer.  Would appreciate any help after spending hours trying to solve the problem.

**Comment by petercreyghton** [comment]
/bin/bash is the default shell on Pi and most Linux distro's, so the error is a bit strange. Which image do you use? Did you run install.sh on a Pi? pls. share some context.

Cheers, Peter

**Comment by chillywit** [comment]
Thank you Peter for quick response.  Here's my setup

2021-03-04-raspios-buster-armhf-lite.img flashed from Windows 10 on 16MB SD card after fresh SD format.  Also tried a different 32MB card with same result.
R.Pi 3 b+ headless on Windows 7 
![IMG_3379](https://user-images.githubusercontent.com/82533173/114760246-f711a400-9d13-11eb-964a-66b92ed17358.jpg)

**Comment by petercreyghton** [comment]
the ^M after /bin/bash suggests you edited the script in Wordpad or other editor that is not Linux-safe.. can you edit the file on the Pi with e.g. Nano to remote the ^M?

**Comment by chillywit** [comment]
I was successful installing the software by editing all files on the R.Pi with Nano.  This was my first experience with R.Pi and getting to know how it works.  Thank you! 

I have one other issue, which is that my radio is apparently not supported.  It's an SDRplay model RSPdx.  I see there's the rtlsdr-ogn file.  I also saw the image file on the SDRplay website for using this radio with R.Pi.  Is there a resource you can direct me to on how I can create a file for using this radio with OGN?

**Comment by petercreyghton** [comment]
I'm not familiar with your radio. I advise you to check the OGN Google group here: https://groups.google.com/g/openglidernetwork, and post your question there if you can't find the info. 

On the other hand, a DVB-T stick costs only around $10, so that might be an alternative.

Cheers, Peter
