### ISSUE TITLE
Install.sh ends unexpected

### ISSUE THREAD

**Issue by Hagoort** [petercreyghton/ogn-install#7]
When running install.sh it doesn't finish as expected. See below. Any advice?

root@raspberrypi:/boot/ogn-install# ./install.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  python-colorzero
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  ntpdate
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 149 kB of archives.
After this operation, 231 kB of additional disk space will be used.
Get:1 http://mirror.serverius.net/raspbian/raspbian buster/main armhf ntpdate armhf 1:4.2.8p12+dfsg-4 [149 kB]
Fetched 149 kB in 0s (417 kB/s)
Selecting previously unselected package ntpdate.
(Reading database ... 40508 files and directories currently installed.)
Preparing to unpack .../ntpdate_1%3a4.2.8p12+dfsg-4_armhf.deb ...
Unpacking ntpdate (1:4.2.8p12+dfsg-4) ...
Setting up ntpdate (1:4.2.8p12+dfsg-4) ...
Processing triggers for man-db (2.8.5-2) ...
sed: can't read version: No such file or directory

**Comment by petercreyghton** [comment]
Looks like the file defining the version of RaspiOS doesn't exist. What RaspiOS image did you install on the SDcard?

**Comment by Hagoort** [comment]
I download latest RaspiOS from https://downloads.raspberrypi.org/raspios_lite_armhf/images/ and selected 
 raspios_lite_armhf-2021-05-28/ | 2021-05-28 16:08 After this I used Etcher.

**Comment by Hagoort** [comment]
What I did exactly is:
download latest RaspiOS from https://downloads.raspberrypi.org/raspios_lite_armhf/images/
used Etcher to flash it to a SD card
downloaded the ogn-install directory from github in Windows and copied it in Windows to /boot/ on the SD card
edit in Windows /boot/ogn-install/OGN-receiver.conf and set the required paramaters ReceiverName, Latitude, Longitude and piUserPassword
edit wpa_supplicant.conf in Windows and copy it in Windows to /boot
create an empty /boot/ssh file to enable SSH access in Windows
boot a Raspberry Pi log in as user pi with password raspberry and run these commands:
sudo -i
cd /boot/ogn-install
./install.sh

**Comment by Hagoort** [comment]
Solved it. Windows automatically puts .txt behind files without a extension. I renamed/removed the files with .txt in the ogn-install directory from within RaspiOS and then the installation worked.

**Comment by Hagoort** [comment]
Hi Peter,

Does your installation automatically calibrate all receiver settings or do I have to use gsmscan and fill in GSMCenterFreq="" and GSMGain=""?

Great work by the way, thanks and greetings Michel

________________________________
